/* empty css                      */(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".demo-btn"),n=document.getElementById("gameIframe"),o=document.getElementById("closeIframeBtn");c&&n&&o&&(c.addEventListener("click",r=>{r.preventDefault();const e=c.getAttribute("data-game-url");n.src=e,n.style.display="block",o.style.display="flex"}),o.addEventListener("click",()=>{n.style.display="none",o.style.display="none",n.src=""}))});document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".menu-button"),n=c.querySelector(".icon"),o=document.querySelector(".modal"),r=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const s=`
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M2 9.5H14M2 6.5H14M2 3.5H14M2 12.5H14" stroke="black" />
</svg>
    `,i=`
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M3.33337 3.33334L12.6667 12.6667M3.33337 12.6667L12.6667 3.33334" stroke="black" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;c.addEventListener("click",()=>{t=!t,n.innerHTML=t?i:s,t?d():l()}),r.forEach(u=>u.addEventListener("click",()=>{l(),n.innerHTML=s,t=!1})),window.addEventListener("scroll",a);function d(){o.style.display="block"}function l(){o.style.display="none"}function a(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function c(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function n(o){const r=document.getElementById(o);if(!r)return;const e=c(),t=r.getBoundingClientRect().top+window.pageYOffset-e;window.scrollTo({top:t,behavior:"smooth"})}if(document.querySelectorAll('a[href*="#"]').forEach(o=>{o.addEventListener("click",function(r){const e=this.getAttribute("href");if(!e)return;const[t,s]=e.split("#");if(!s)return;const i=window.location.pathname.split("/").pop();!(t===""||t==="./"||t===i||t==="./"+i)||!document.getElementById(s)||(r.preventDefault(),n(s))})}),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{n(o)},300)}});document.addEventListener("DOMContentLoaded",function(){const c=document.getElementById("cookie-popup"),n=document.getElementById("accept-cookies"),o=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(c.style.display="block"),n.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),c.style.display="none"}),o.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),c.style.display="none"})});
//# sourceMappingURL=index.js.map
